version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx.conf:/usr/local/nginx/conf/nginx.conf
            - ./www:/usr/share/nginx/html
    php:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        expose:
          - 9000
        volumes:
            - ./www:/var/www
    db:
      image: mariadb:latest
      restart: always
      ports:
            - "3306:3306"
      volumes:
          - ./my.cnf:/etc/mysql/my.cnf
          - ./.db:/var/lib/mysql
      environment:
        MARIADB_USER: 'mysmallpet_db'
        MARIADB_PASSWORD: 'mysmallpet_db_2021'
        MARIADB_DATABASE: 'mysmallpet_db'
        MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'

    phpmyadmin:
      image: phpmyadmin
      ports:
        - 8082:80
      environment:
        - PMA_ARBITRARY=1
volumes:
    mysqldata: {}
