<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Каталог");
?><?$APPLICATION->IncludeComponent(
	"bitrix:catalog", 
	"al1_custom", 
	array(
		"ACCESSORIES_PROP" => "-",
		"ACTION_VARIABLE" => "action",
		"ADDITIONAL_PICT_PROP" => "MORE_PHOTO",
		"ADD_ELEMENT_CHAIN" => "Y",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"ADD_SECTIONS_CHAIN" => "Y",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"ALSO_BUY_ELEMENT_COUNT" => "5",
		"ALSO_BUY_MIN_BUYES" => "1",
		"ARTICLE_PROP" => "ARTIKUL_2",
		"BASKET_URL" => "/personal/cart/",
		"BIG_DATA_RCM_TYPE" => "bestsell",
		"BRAND_IBLOCK_BRAND_PROP" => "-",
		"BRAND_IBLOCK_ID" => "1",
		"BRAND_LOGO_PROP" => "-",
		"BRAND_PROP" => "CML2_MANUFACTURER",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "N",
		"CATALOG_VIEW_MODE" => "VIEW_ELEMENTS",
		"COMPARE_ELEMENT_SORT_FIELD" => "sort",
		"COMPARE_ELEMENT_SORT_ORDER" => "asc",
		"COMPARE_FIELD_CODE" => array(
			0 => "PREVIEW_PICTURE",
			1 => "DETAIL_PICTURE",
			2 => "",
		),
		"COMPARE_NAME" => "CATALOG_COMPARE_LIST",
		"COMPARE_OFFERS_FIELD_CODE" => array(
			0 => "PREVIEW_PICTURE",
			1 => "DETAIL_PICTURE",
			2 => "",
		),
		"COMPARE_OFFERS_PROPERTY_CODE" => array(
			0 => "WEIGHT",
			1 => "SKU_COLOR_2",
			2 => "SKU_COLOR_1",
			3 => "SKU_COLOR",
			4 => "SKU_SIZE",
			5 => "CML2_ARTICKLE",
			6 => "SKU_TKAN",
			7 => "SKU_COLOR_ZERO",
			8 => "",
		),
		"COMPARE_PROPERTY_CODE" => array(
			0 => "",
			1 => "CML2_ARTICKLE",
			2 => "DOSTAVKA_INFO",
			3 => "BRANDS",
			4 => "YEARS_LIMIT",
			5 => "TEST_COLOR",
			6 => "YEAR",
			7 => "RAMA",
			8 => "VILKA",
			9 => "OBODA",
			10 => "TORMOZA",
			11 => "POSHIV",
			12 => "VOZRASTNAYA_GRUPPA",
			13 => "TEST_MULTI_PROP",
			14 => "DOSTAVKA",
			15 => "",
		),
		"COMPATIBLE_MODE" => "Y",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO",
		"CONVERT_CURRENCY" => "Y",
		"COUNT_RESULT_NOT_CATALOG" => "10",
		"CURRENCY_ID" => "RUB",
		"DELIVERY_PROP" => "-",
		"DETAIL_BACKGROUND_IMAGE" => "-",
		"DETAIL_BROWSER_TITLE" => "-",
		"DETAIL_CHECK_SECTION_ID_VARIABLE" => "N",
		"DETAIL_DISPLAY_PREVIEW_TEXT_MODE" => "E",
		"DETAIL_MAIN_BLOCK_PROPERTY_CODE" => array(
		),
		"DETAIL_META_DESCRIPTION" => "-",
		"DETAIL_META_KEYWORDS" => "-",
		"DETAIL_OFFERS_FIELD_CODE" => array(
			0 => "ID",
			1 => "CODE",
			2 => "XML_ID",
			3 => "NAME",
			4 => "",
		),
		"DETAIL_OFFERS_PROPERTY_CODE" => array(
			0 => "WEIGHT",
			1 => "FOR_DRY",
			2 => "REKOMENDATSII",
			3 => "ARTICLE_1",
			4 => "ARTIKUL_1",
			5 => "SODERZHANIE_PITATELNYKH_VESHCHESTV_1",
			6 => "CML2_ARTICLE",
			7 => "ARTIKUL",
			8 => "MORE_PHOTO",
			9 => "CML2_MANUFACTURER",
			10 => "SODERZHANIE_PITATELNYKH_VESHCHESTV_2",
			11 => "FILES",
			12 => "VOZRAST_1",
			13 => "MASSA",
			14 => "STRANA_PROIZVODITEL",
			15 => "TIP_KORMA",
			16 => "VOZRAST_2",
			17 => "VOZRAST",
			18 => "MASSA_1",
			19 => "SODERZHANIE_PITATELNYKH_VESHCHESTV",
			20 => "SOSTAV",
			21 => "STRANA_PROIZVODITEL_1",
			22 => "TIP_KORMA_1",
			23 => "TIP_KORMA_2",
			24 => "USLOVIYA_KHRANENIYA",
			25 => "SKU_COLOR_2",
			26 => "SKU_COLOR_1",
			27 => "SKU_COLOR",
			28 => "SKU_SIZE",
			29 => "CML2_ARTICKLE",
			30 => "SKU_TKAN",
			31 => "SKU_COLOR_ZERO",
			32 => "",
		),
		"DETAIL_PROPERTY_CODE" => array(
			0 => "CML2_MANUFACTURER",
			1 => "AGE",
			2 => "REKOMENDATSII",
			3 => "VES",
			4 => "SODERZHANIE_PITATELNYKH_VESHCHESTV_1",
			5 => "FOR_DOGS",
			6 => "CML2_ARTICLE",
			7 => "ARTIKUL",
			8 => "ARTIKUL_1",
			9 => "VES__1",
			10 => "SIZE",
			11 => "SODERZHANIE_PITATELNYKH_VESHCHESTV_2",
			12 => "SUKHOY",
			13 => "VOZRAST_1",
			14 => "MASSA",
			15 => "STRANA_PROIZVODITEL",
			16 => "TIP_KORMA",
			17 => "VOZRAST_2",
			18 => "VOZRAST",
			19 => "MASSA_1",
			20 => "SODERZHANIE_PITATELNYKH_VESHCHESTV",
			21 => "SOSTAV",
			22 => "STRANA_PROIZVODITEL_1",
			23 => "TIP_KORMA_1",
			24 => "TIP_KORMA_2",
			25 => "USLOVIYA_KHRANENIYA",
			26 => "CML2_ARTICKLE",
			27 => "DOSTAVKA_INFO",
			28 => "FOR_MEN",
			29 => "FOR_WOMEN",
			30 => "BRANDS",
			31 => "YEARS_LIMIT",
			32 => "TEST_COLOR",
			33 => "YEAR",
			34 => "RAMA",
			35 => "VILKA",
			36 => "OBODA",
			37 => "TORMOZA",
			38 => "POSHIV",
			39 => "VOZRASTNAYA_GRUPPA",
			40 => "TEST_MULTI_PROP",
			41 => "DOSTAVKA",
			42 => "",
		),
		"DETAIL_SET_CANONICAL_URL" => "Y",
		"DETAIL_SET_VIEWED_IN_COMPONENT" => "N",
		"DETAIL_SOCIAL_SERVICES" => array(
			0 => "gplus",
			1 => "odnoklassniki",
			2 => "telegram",
			3 => "twitter",
			4 => "viber",
			5 => "vkontakte",
			6 => "whatsapp",
			7 => "",
		),
		"DETAIL_STRICT_SECTION_CHECK" => "N",
		"DISABLE_INIT_JS_IN_COMPONENT" => "Y",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_ELEMENT_SELECT_BOX" => "N",
		"DISPLAY_TOP_PAGER" => "Y",
		"ELEMENT_SORT_FIELD" => "sort",
		"ELEMENT_SORT_FIELD2" => "id",
		"ELEMENT_SORT_ORDER" => "asc",
		"ELEMENT_SORT_ORDER2" => "desc",
		"ERROR_EMPTY_ITEMS" => "Y",
		"FEATURE_FILTER_USER_FIELDS" => "-",
		"FIELDS" => array(
			0 => "",
			1 => "",
		),
		"FILE_404" => "",
		"FILTER_COLLAPSE_ACTIVE" => "Y",
		"FILTER_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"FILTER_NAME" => "",
		"FILTER_OFFERS_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"FILTER_OFFERS_PROPERTY_CODE" => array(
			0 => "WEIGHT",
			1 => "",
		),
		"FILTER_PRICES_GROUPED" => "",
		"FILTER_PRICES_GROUPED_FOR" => "products",
		"FILTER_PRICE_CODE" => array(
			0 => "BASE",
		),
		"FILTER_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"FILTER_SCROLL_PROPS" => array(
		),
		"FILTER_SEARCH_PROPS" => array(
		),
		"FORUM_ID" => "1",
		"GIFTS_DETAIL_BLOCK_TITLE" => "Выберите один из подарков",
		"GIFTS_DETAIL_HIDE_BLOCK_TITLE" => "N",
		"GIFTS_DETAIL_PAGE_ELEMENT_COUNT" => "3",
		"GIFTS_DETAIL_TEXT_LABEL_GIFT" => "Подарок",
		"GIFTS_MAIN_PRODUCT_DETAIL_BLOCK_TITLE" => "Выберите один из товаров, чтобы получить подарок",
		"GIFTS_MAIN_PRODUCT_DETAIL_HIDE_BLOCK_TITLE" => "N",
		"GIFTS_MAIN_PRODUCT_DETAIL_PAGE_ELEMENT_COUNT" => "5",
		"GIFTS_MESS_BTN_BUY" => "Выбрать",
		"GIFTS_SECTION_LIST_BLOCK_TITLE" => "Подарки к товарам этого раздела",
		"GIFTS_SECTION_LIST_HIDE_BLOCK_TITLE" => "N",
		"GIFTS_SECTION_LIST_PAGE_ELEMENT_COUNT" => "4",
		"GIFTS_SECTION_LIST_TEXT_LABEL_GIFT" => "Подарок",
		"GIFTS_SHOW_DISCOUNT_PERCENT" => "Y",
		"GIFTS_SHOW_IMAGE" => "Y",
		"GIFTS_SHOW_NAME" => "Y",
		"GIFTS_SHOW_OLD_PRICE" => "Y",
		"HIDE_NOT_AVAILABLE" => "N",
		"HIDE_NOT_AVAILABLE_OFFERS" => "N",
		"IBLOCK_ID" => "13",
		"IBLOCK_TYPE" => "1c_catalog",
		"ICON_DEALS_PROP" => "-",
		"ICON_DISCOUNT_PROP" => "-",
		"ICON_MEN_PROP" => "-",
		"ICON_NOVELTY_PROP" => "-",
		"ICON_WOMEN_PROP" => "-",
		"INCLUDE_SUBSECTIONS" => "A",
		"INSTANT_RELOAD" => "Y",
		"KREDIT_URL" => "/kredit/",
		"LIKES_COUNT_PROP" => "-",
		"LINE_ELEMENT_COUNT" => "3",
		"LINKED_ITEMS_PROPS" => array(
		),
		"LINK_ELEMENTS_URL" => "link.php?PARENT_ELEMENT_ID=#ELEMENT_ID#",
		"LINK_IBLOCK_ID" => "",
		"LINK_IBLOCK_TYPE" => "",
		"LINK_PROPERTY_SID" => "",
		"LIST_BROWSER_TITLE" => "-",
		"LIST_DISPLAY_PREVIEW_TEXT" => "Y",
		"LIST_META_DESCRIPTION" => "-",
		"LIST_META_KEYWORDS" => "-",
		"LIST_OFFERS_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"LIST_OFFERS_LIMIT" => "0",
		"LIST_OFFERS_PROPERTY_CODE" => array(
			0 => "WEIGHT",
			1 => "SKU_COLOR_2",
			2 => "SKU_COLOR_1",
			3 => "SKU_COLOR",
			4 => "SKU_SIZE",
			5 => "SKU_TKAN",
			6 => "SKU_COLOR_ZERO",
			7 => "",
		),
		"LIST_PROPERTY_CODE" => array(
			0 => "",
			1 => "BRANDS",
			2 => "",
		),
		"LIST_SOCIAL_SERVICES" => array(
			0 => "gplus",
			1 => "odnoklassniki",
			2 => "telegram",
			3 => "twitter",
			4 => "viber",
			5 => "vkontakte",
			6 => "whatsapp",
			7 => "",
		),
		"MAIN_TITLE" => "Наличие",
		"MESSAGES_PER_PAGE" => "10",
		"MIN_AMOUNT" => "10",
		"NOVELTY_TIME" => "720",
		"OFFERS_CART_PROPERTIES" => array(
			0 => "WEIGHT",
			1 => "ARTICLE_1",
			2 => "ARTIKUL_1",
			3 => "CML2_ARTICLE",
			4 => "ARTIKUL",
			5 => "MASSA",
			6 => "MASSA_1",
		),
		"OFFERS_SORT_FIELD" => "sort",
		"OFFERS_SORT_FIELD2" => "id",
		"OFFERS_SORT_ORDER" => "asc",
		"OFFERS_SORT_ORDER2" => "desc",
		"OFFER_ADDITIONAL_PICT_PROP" => "-",
		"OFFER_ARTICLE_PROP" => "-",
		"OFFER_FILTER_SCROLL_PROPS" => array(
		),
		"OFFER_FILTER_SEARCH_PROPS" => array(
		),
		"OFFER_TREE_BTN_PROPS" => array(
		),
		"OFFER_TREE_COLOR_PROPS" => array(
		),
		"OFFER_TREE_PROPS" => array(
		),
		"PAGER_BASE_LINK" => "",
		"PAGER_BASE_LINK_ENABLE" => "Y",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_PARAMS_NAME" => "arrPager",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => "al",
		"PAGER_TITLE" => "Товары",
		"PAGE_ELEMENT_COUNT" => "30",
		"PARTIAL_PRODUCT_PROPERTIES" => "Y",
		"PATH_TO_SMILE" => "/bitrix/images/forum/smile/",
		"POPUP_DETAIL_VARIABLE" => "ON_LUPA",
		"PREVIEW_TRUNCATE_LEN" => "128",
		"PRICE_CODE" => array(
			0 => "BASE",
		),
		"PRICE_VAT_INCLUDE" => "Y",
		"PRICE_VAT_SHOW_VALUE" => "N",
		"PRODUCT_ID_VARIABLE" => "id",
		"PRODUCT_PROPERTIES" => array(
		),
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PRODUCT_QUANTITY_VARIABLE" => "",
		"REVIEW_AJAX_POST" => "Y",
		"SECTIONS_SHOW_PARENT_NAME" => "Y",
		"SECTIONS_VIEW_MODE" => "TILE",
		"SECTION_BACKGROUND_IMAGE" => "-",
		"SECTION_COUNT_ELEMENTS" => "Y",
		"SECTION_ID_VARIABLE" => "SECTION_ID",
		"SECTION_PICTURE_HEIGHT" => "",
		"SECTION_PICTURE_WIDTH" => "",
		"SECTION_TOP_DEPTH" => "4",
		"SECTION_USER_FIELDS" => array(
			0 => "",
			1 => "UF_PRICE_FROM",
			2 => "UF_PRICE_TO",
			3 => "",
		),
		"SEF_FOLDER" => "/catalog/",
		"SEF_MODE" => "Y",
		"SET_LAST_MODIFIED" => "Y",
		"SET_STATUS_404" => "Y",
		"SET_TITLE" => "Y",
		"SHOW_404" => "Y",
		"SHOW_DEACTIVATED" => "N",
		"SHOW_DISCOUNT_PERCENT" => "Y",
		"SHOW_EMPTY_STORE" => "Y",
		"SHOW_GENERAL_STORE_INFORMATION" => "N",
		"SHOW_LINK_TO_FORUM" => "N",
		"SHOW_OLD_PRICE" => "Y",
		"SHOW_PRICE_COUNT" => "1",
		"SHOW_SECTION_DESCRIPTION" => "top",
		"SHOW_SECTION_PICTURE" => "Y",
		"SHOW_SKU_DESCRIPTION" => "N",
		"SHOW_TOP_ELEMENTS" => "N",
		"SIZE_TABLE_USER_FIELD_CODE" => "UF_SIZE_TABLE",
		"SOCIAL_COPY" => "first",
		"SOCIAL_COUNTER" => "Y",
		"SOCIAL_LIMIT" => "",
		"SOCIAL_SIZE" => "m",
		"STORES" => array(
			0 => "1",
			1 => "2",
			2 => "",
		),
		"STORE_PATH" => "/store/#store_id#",
		"TAB_IBLOCK_PROPS" => array(
			0 => "",
			1 => "DOCS",
			2 => "ACCESSORIES",
			3 => "",
		),
		"TEMPLATE_AJAXID" => "catalog",
		"URL_TEMPLATES_READ" => "",
		"USER_CONSENT" => "Y",
		"USER_CONSENT_ID" => "1",
		"USER_CONSENT_IS_CHECKED" => "Y",
		"USER_CONSENT_IS_LOADED" => "N",
		"USER_FIELDS" => array(
			0 => "",
			1 => "",
		),
		"USE_AJAXPAGES" => "Y",
		"USE_ALSO_BUY" => "Y",
		"USE_AUTO_AJAXPAGES" => "N",
		"USE_BIG_DATA" => "Y",
		"USE_BUY1CLICK" => "Y",
		"USE_CAPTCHA" => "Y",
		"USE_COMPARE" => "Y",
		"USE_ELEMENT_COUNTER" => "Y",
		"USE_FILTER" => "Y",
		"USE_GIFTS_DETAIL" => "Y",
		"USE_GIFTS_MAIN_PR_SECTION_LIST" => "Y",
		"USE_GIFTS_SECTION" => "N",
		"USE_KREDIT" => "Y",
		"USE_LIKES" => "Y",
		"USE_MAIN_ELEMENT_SECTION" => "Y",
		"USE_MIN_AMOUNT" => "Y",
		"USE_PICTURE_GALLERY" => "Y",
		"USE_PICTURE_ZOOM" => "Y",
		"USE_PRICE_COUNT" => "N",
		"USE_PRODUCT_QUANTITY" => "Y",
		"USE_QUANTITY_AND_STORES" => "Y",
		"USE_REVIEW" => "Y",
		"USE_SHARE" => "Y",
		"USE_STORE" => "N",
		"COMPONENT_TEMPLATE" => "al1_custom",
		"SEF_URL_TEMPLATES" => array(
			"sections" => "",
			"section" => "#SECTION_CODE_PATH#/",
			"element" => "#SECTION_CODE_PATH#/#ELEMENT_CODE#/",
			"compare" => "compare/?action=#ACTION_CODE#",
			"smart_filter" => "#SECTION_CODE_PATH#/filter/#SMART_FILTER_PATH#/apply/",
		),
		"VARIABLE_ALIASES" => array(
			"compare" => array(
				"ACTION_CODE" => "action",
			),
		)
	),
	false
);?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>